apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: spark-worker
  name: spark-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - name: spark-worker
        image:  halbritt/docker-spark:latest
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
        imagePullPolicy : "IfNotPresent"
        ports:
            - containerPort: 4040
            - containerPort: 8081
            - containerPort: 7078
        resources :
          requests :
            cpu : 1
            memory : "512Mi"
          limits :
             cpu : 1
             memory : "1Gi"

