kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: halbritt/docker-spark:latest
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
